Vagrant::Config.run do |config|
  
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Assign this VM to a host only network IP, allowing you to access it
  # via the IP.
  config.vm.network :hostonly, "33.33.33.10"
  # config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 80, 8080

  config.vm.share_folder("web-app", "/home/vagrant/web-app", "../", :owner => "vagrant")

  config.vm.provision :chef_solo do |chef|
    # This path will be expanded relative to the project directory
    chef.cookbooks_path = "cookbooks"

    chef.add_recipe("vagrant_main")
    # Uncomment the recipes you would want this app to use
    # chef.add_recipe("vagrant_main::mysql")
    # chef.add_recipe("vagrant_main::rabbitmq")
    chef.json = {
      "xdebug" => {
        "remote_enable" => "1",
        "remote_host" => "33.33.33.1"
      }
    }
  end
end
